version: '3.8'
services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=elearning5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  tomcat:
    build: .
    ports:
      - "8080:8080"
    container_name: tomcat
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: